stages:
    - test
    - build
    - deploy

frontend-test:
    image: node:latest
    stage: test
    before_script:
        - cd frontend
        - yarn
    script:
        - yarn test

backend-test:
    image: node:latest
    stage: test
    before_script:
        - cd backend
        - npm install
    script:
        - npm run unittest

frontend-build:
    image: node:latest
    stage: build
    before_script:
        - cd frontend
        - npm install
    script:
        - npm run build
    only:
        - /^main$/

backend-build:
    image: node:latest
    stage: build
    before_script:
        - cd backend
        - npm install
    script:
        - npm run build
    only:
        - /^main$/

frontend-deploy:
    image: docker:latest
    stage: deploy
    before_script:
        - cd frontend
    script:
        - docker build -t $DOCKER_ID/$DOCKER_FRONTEND_REPO .
        - docker login -u $DOCKER_ID -p $DOCKER_TOKEN
        - docker push $DOCKER_ID/$DOCKER_FRONTEND_REPO
    after_script:
        - docker logout
