stages:
    - test

frontend-test:
    image: node:latest
    stage: test
    before_script:
        - cd frontend
        - yarn
    script:
        - yarn test

backend-test:
    image: node:latest
    stage: test
    before_script:
        - cd backend
        - npm install
    script:
        - npm run unittest
